// Generated by CoffeeScript 1.3.3
(function() {
  var codename, copy_data_to, express, fs, log, minify, path, socketio, uglify, uuid, viewhelpers, views, zappa,
    __slice = [].slice;

  zappa = {
    version: '0.3.3'
  };

  codename = 'The Gumbo Variations';

  log = console.log;

  fs = require('fs');

  path = require('path');

  uuid = require('node-uuid');

  express = require('express');

  socketio = require('socket.io');

  uglify = require('uglify-js');

  minify = function(js) {
    var ast;
    ast = uglify.parser.parse(js);
    ast = uglify.uglify.ast_mangle(ast);
    ast = uglify.uglify.ast_squeeze(ast);
    return uglify.uglify.gen_code(ast);
  };

  copy_data_to = function(recipient, sources) {
    var k, obj, v, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = sources.length; _i < _len; _i++) {
      obj = sources[_i];
      _results.push((function() {
        var _results1;
        _results1 = [];
        for (k in obj) {
          v = obj[k];
          if (!recipient[k]) {
            _results1.push(recipient[k] = v);
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  };

  views = {};

  viewhelpers = {};

  express.View.prototype.__defineGetter__('exists', function() {
    var id, p;
    p = this.path.replace(this.root + '/', '');
    id = p.split('/')[0];
    if (views[p]) {
      return true;
    }
    p = p.replace(path.extname(p), '');
    if (views[p]) {
      return true;
    }
    p = this.path.replace(id + '/', '');
    try {
      fs.statSync(p);
      return true;
    } catch (err) {
      return false;
    }
  });

  express.View.prototype.__defineGetter__('contents', function() {
    var id, p;
    p = this.path.replace(this.root + '/', '');
    id = p.split('/')[0];
    if (views[p]) {
      return views[p];
    }
    p = p.replace(path.extname(p), '');
    if (views[p]) {
      return views[p];
    }
    p = this.path.replace(id + '/', '');
    return fs.readFileSync(p, 'utf8');
  });

  zappa.app = function(func) {
    var app, context, helpers, io, postrenders, replace_partials, route, verb, ws_handlers, zappa_used, _fn, _i, _len, _ref;
    context = {
      id: uuid(),
      zappa: zappa,
      express: express
    };
    context.root = path.dirname(module.parent.filename);
    ws_handlers = {};
    helpers = {};
    postrenders = {};
    app = context.app = express.createServer();
    io = context.io = socketio.listen(app);
    zappa_used = false;
    app.set('view engine', 'html');
    replace_partials = function(src, pf) {
      return src.replace(/@partial \w+/g, function(match, pos, contents, s) {
        var fn;
        fn = match.slice('@partial'.length + 1);
        return pf(fn);
      });
    };
    app.register('.html', {
      compile: function(str, options) {
        return function(locals) {
          if (options.body) {
            str = str.replace(/@body/g, options.body);
          }
          if (options.initdata && !options.isPartial && !options.isLayout) {
            str = str.replace(/_initdata/g, JSON.stringify(options.initdata));
          }
          return replace_partials(str, options.partial);
        };
      }
    });
    app.set('views', path.join(context.root, '/views'));
    _ref = ['get', 'post', 'put', 'del'];
    _fn = function(verb) {
      return context[verb] = function() {
        var k, v, _ref1, _results;
        if (arguments.length > 1) {
          return route({
            verb: verb,
            path: arguments[0],
            handler: arguments[1]
          });
        } else {
          _ref1 = arguments[0];
          _results = [];
          for (k in _ref1) {
            v = _ref1[k];
            _results.push(route({
              verb: verb,
              path: k,
              handler: v
            }));
          }
          return _results;
        }
      };
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      verb = _ref[_i];
      _fn(verb);
    }
    context.js = function(obj) {
      var js, k, v, _results;
      _results = [];
      for (k in obj) {
        v = obj[k];
        js = String(v);
        if (app.settings['minify']) {
          js = minify(js);
        }
        _results.push(route({
          verb: 'get',
          path: k,
          handler: js,
          contentType: 'js'
        }));
      }
      return _results;
    };
    context.css = function(obj) {
      var css, k, v, _results;
      _results = [];
      for (k in obj) {
        v = obj[k];
        css = String(v);
        _results.push(route({
          verb: 'get',
          path: k,
          handler: css,
          contentType: 'css'
        }));
      }
      return _results;
    };
    context.helper = function(obj) {
      var k, v, _results;
      _results = [];
      for (k in obj) {
        v = obj[k];
        _results.push(helpers[k] = v);
      }
      return _results;
    };
    context.on = function(obj) {
      var k, v, _results;
      _results = [];
      for (k in obj) {
        v = obj[k];
        _results.push(ws_handlers[k] = v);
      }
      return _results;
    };
    context.view = function(obj) {
      var k, v, _results;
      _results = [];
      for (k in obj) {
        v = obj[k];
        _results.push(views["" + context.id + "/" + k] = v);
      }
      return _results;
    };
    context.register = function(obj) {
      var k, v, _results;
      _results = [];
      for (k in obj) {
        v = obj[k];
        _results.push(app.register('.' + k, v));
      }
      return _results;
    };
    context.set = function(obj) {
      var k, v, _results;
      _results = [];
      for (k in obj) {
        v = obj[k];
        _results.push(app.set(k, v));
      }
      return _results;
    };
    context.enable = function() {
      var i, _j, _len1, _results;
      _results = [];
      for (_j = 0, _len1 = arguments.length; _j < _len1; _j++) {
        i = arguments[_j];
        _results.push(app.enable(i));
      }
      return _results;
    };
    context.disable = function() {
      var i, _j, _len1, _results;
      _results = [];
      for (_j = 0, _len1 = arguments.length; _j < _len1; _j++) {
        i = arguments[_j];
        _results.push(app.disable(i));
      }
      return _results;
    };
    context.use = function() {
      var a, k, use, v, zappa_middleware, _j, _len1, _results;
      zappa_middleware = {
        "static": function(p) {
          if (p == null) {
            p = path.join(context.root, '/public');
          }
          return express["static"](p);
        },
        zappa: function() {
          return function(req, res, next) {
            var send;
            send = function(code) {
              res.contentType('js');
              return res.send(code);
            };
            return next();
          };
        }
      };
      use = function(name, arg) {
        if (arg == null) {
          arg = null;
        }
        if (name === 'zappa') {
          zappa_used = true;
        }
        if (zappa_middleware[name]) {
          return app.use(zappa_middleware[name](arg));
        } else if (typeof express[name] === 'function') {
          return app.use(express[name](arg));
        }
      };
      _results = [];
      for (_j = 0, _len1 = arguments.length; _j < _len1; _j++) {
        a = arguments[_j];
        switch (typeof a) {
          case 'function':
            _results.push(app.use(a));
            break;
          case 'string':
            _results.push(use(a));
            break;
          case 'object':
            _results.push((function() {
              var _results1;
              _results1 = [];
              for (k in a) {
                v = a[k];
                _results1.push(use(k, v));
              }
              return _results1;
            })());
            break;
          default:
            _results.push(void 0);
        }
      }
      return _results;
    };
    context.configure = function(p) {
      var k, v, _results;
      if (typeof p === 'function') {
        return app.configure(p);
      } else {
        _results = [];
        for (k in p) {
          v = p[k];
          _results.push(app.configure(k, v));
        }
        return _results;
      }
    };
    context.settings = app.settings;
    context.include = function(p) {
      var sub;
      sub = require(path.join(context.root, p));
      return sub.include.apply(context, [context]);
    };
    route = function(r) {
      var qry;
      qry = app.lookup[r.verb](r.path);
      if (qry.length > 0) {
        console.log("" + r.verb + " " + r.path + " exists! Replace it");
        app.remove[r.verb](r.path);
      }
      if (typeof r.handler === 'string') {
        return app[r.verb](r.path, function(req, res) {
          if (r.contentType != null) {
            res.contentType(r.contentType);
          }
          return res.send(r.handler);
        });
      } else {
        return app[r.verb](r.path, function(req, res, next) {
          var ctx, data, helper, name, render, result, _fn1;
          ctx = {
            app: app,
            settings: app.settings,
            request: req,
            query: req.query,
            params: req.params,
            body: req.body,
            session: req.session,
            response: res,
            next: next,
            send: function() {
              return res.send.apply(res, arguments);
            },
            redirect: function() {
              return res.redirect.apply(res, arguments);
            },
            render: function() {
              var k, v, _ref1, _results;
              if (typeof arguments[0] !== 'object') {
                return render.apply(this, arguments);
              } else {
                _ref1 = arguments[0];
                _results = [];
                for (k in _ref1) {
                  v = _ref1[k];
                  _results.push(render.apply(this, [k, v]));
                }
                return _results;
              }
            }
          };
          render = function() {
            var args, _ref1;
            args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            args[0] = context.id + '/' + args[0];
            if ((_ref1 = args[1]) == null) {
              args[1] = {};
            }
            if (typeof args[1] === 'function') {
              args.splice(1, 0, {});
            }
            if (app.settings['databag']) {
              args[1].params = data;
            }
            return res.render.apply(res, args);
          };
          _fn1 = function(name, helper) {
            return ctx[name] = function() {
              var args;
              args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
              args.push(ctx);
              return helper.apply(ctx, args);
            };
          };
          for (name in helpers) {
            helper = helpers[name];
            _fn1(name, helper);
          }
          if (app.settings['databag']) {
            data = {};
            copy_data_to(data, [req.query, req.params, req.body]);
          }
          switch (app.settings['databag']) {
            case 'this':
              result = r.handler.apply(data, [ctx]);
              break;
            case 'param':
              result = r.handler.apply(ctx, [data]);
              break;
            default:
              result = r.handler.apply(ctx, [ctx]);
          }
          if (r.contentType != null) {
            res.contentType(r.contentType);
          }
          if (typeof result === 'string') {
            return res.send(result);
          } else {
            return result;
          }
        });
      }
    };
    io.sockets.on('connection', function(socket) {
      var build_ctx, c, ctx, h, name, _results;
      c = {};
      build_ctx = function() {
        var ctx, helper, name, _fn1;
        ctx = {
          app: app,
          io: io,
          settings: app.settings,
          socket: socket,
          id: socket.id,
          emit: function() {
            var k, v, _ref1, _results;
            if (typeof arguments[0] !== 'object') {
              return socket.emit.apply(socket, arguments);
            } else {
              _ref1 = arguments[0];
              _results = [];
              for (k in _ref1) {
                v = _ref1[k];
                _results.push(socket.emit.apply(socket, [k, v]));
              }
              return _results;
            }
          },
          broadcast: function() {
            var k, v, _ref1, _results;
            if (typeof arguments[0] !== 'object') {
              return socket.broadcast.emit.apply(socket.broadcast, arguments);
            } else {
              _ref1 = arguments[0];
              _results = [];
              for (k in _ref1) {
                v = _ref1[k];
                _results.push(socket.broadcast.emit.apply(socket.broadcast, [k, v]));
              }
              return _results;
            }
          }
        };
        _fn1 = function(name, helper) {
          return ctx[name] = function() {
            return helper.apply(ctx, arguments);
          };
        };
        for (name in helpers) {
          helper = helpers[name];
          _fn1(name, helper);
        }
        return ctx;
      };
      ctx = build_ctx();
      if (ws_handlers.connection != null) {
        ws_handlers.connection.apply(ctx, [ctx]);
      }
      socket.on('disconnect', function() {
        ctx = build_ctx();
        if (ws_handlers.disconnect != null) {
          return ws_handlers.disconnect.apply(ctx, [ctx]);
        }
      });
      _results = [];
      for (name in ws_handlers) {
        h = ws_handlers[name];
        _results.push((function(name, h) {
          if (name !== 'connection' && name !== 'disconnect') {
            return socket.on(name, function(data) {
              ctx = build_ctx();
              ctx.data = data;
              switch (app.settings['databag']) {
                case 'this':
                  return h.apply(data, [ctx]);
                case 'param':
                  return h.apply(ctx, [data]);
                default:
                  return h.apply(ctx, [ctx]);
              }
            });
          }
        })(name, h));
      }
      return _results;
    });
    func.apply(context, [context]);
    return context;
  };

  zappa.run = function() {
    var a, app, host, port, root_function, zapp, _i, _len, _ref;
    host = null;
    port = 3000;
    root_function = null;
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      a = arguments[_i];
      switch (typeof a) {
        case 'string':
          if (isNaN(Number(a))) {
            host = a;
          } else {
            port = Number(a);
          }
          break;
        case 'number':
          port = a;
          break;
        case 'function':
          root_function = a;
      }
    }
    zapp = zappa.app(root_function);
    app = zapp.app;
    if (host) {
      app.listen(port, host);
    } else {
      app.listen(port);
    }
    log('Express server listening on port %d in %s mode', (_ref = app.address()) != null ? _ref.port : void 0, app.settings.env);
    log("SZappa " + zappa.version + " \"" + codename + "\" orchestrating the show");
    return zapp;
  };

  module.exports = zappa.run;

  module.exports.run = zappa.run;

  module.exports.app = zappa.app;

  module.exports.adapter = zappa.adapter;

  module.exports.version = zappa.version;

}).call(this);
